---
- name: Configure containerd apt repository
  ansible.builtin.import_tasks: 10-repo.yml

- name: Install containerd package
  ansible.builtin.import_tasks: 20-install.yml

- name: Configure containerd runtime
  ansible.builtin.import_tasks: 30-config.yml

- name: Verify containerd
  ansible.builtin.import_tasks: 40-verify.yml
