---
# ../tasks/10-repo.yml
calico_repo_name: projectcalico
calico_repo_url: https://docs.tigera.io/calico/charts

# ../tasks/20-install.yml
calico_namespace: calico-system

calico_chart_ref: projectcalico/tigera-operator
calico_release_name: calico

calico_crd_chart: projectcalico/crd.projectcalico.org.v1
calico_crd_release_name: calico-crds

calico_values_file_path: /tmp/calico-values.yaml
calico_kubeconfig_path: "{{ kubeconfig_user_home }}/.kube/config"

# ../tasks/30-verify.yml
calico_wait_timeout: 300s
