---
# - name: 20-install - Create Calico namespace
#   ansible.builtin.command: kubectl create namespace {{ calico_namespace }}
#   environment:
#     KUBECONFIG: "{{ calico_kubeconfig_path }}"
#   register: calico_ns
#   changed_when: "'created' in calico_ns.stdout"
#   failed_when: calico_ns.rc != 0 and 'AlreadyExists' not in calico_ns.stderr

- name: 20-install - Install Calico CRDs
  ansible.builtin.shell: >-
    helm template {{ calico_crd_release_name }} {{ calico_crd_chart }}
    --version {{ calico_version }}
    | kubectl apply --server-side --force-conflicts -f -
  environment:
    KUBECONFIG: "{{ calico_kubeconfig_path }}"
  register: calico_crd_apply
  changed_when: >-
    'created' in calico_crd_apply.stdout
    or 'configured' in calico_crd_apply.stdout
    or 'serverside-applied' in calico_crd_apply.stdout

- name: 20-install - Render Calico Helm values file
  ansible.builtin.template:
    src: values.yaml.j2
    dest: "{{ calico_values_file_path }}"
    mode: "0644"

- name: 20-install - Install Calico Tigera Operator via Helm
  ansible.builtin.command: >-
    helm upgrade --install {{ calico_release_name }} {{ calico_chart_ref }}
    --create-namespace
    --namespace {{ calico_namespace }}
    --version {{ calico_version }}
    -f {{ calico_values_file_path }}
  environment:
    KUBECONFIG: "{{ calico_kubeconfig_path }}"
