---
- name: 30-init - Check if cluster is already initialized
  ansible.builtin.stat:
    path: "{{ kubernetes_admin_conf }}"
  register: kubeadm_admin_conf

- name: 30-init - Check active swap before kubeadm init
  ansible.builtin.command: swapon --show
  register: swapon_status
  changed_when: false
  failed_when: false
  when: not kubeadm_admin_conf.stat.exists

- name: 30-init - Disable swap before kubeadm init
  ansible.builtin.command: swapoff -a
  when:
    - not kubeadm_admin_conf.stat.exists
    - swapon_status.stdout | length > 0
  register: swapoff_result
  changed_when: swapoff_result.rc == 0

- name: 30-init - Initialize Kubernetes control plane
  ansible.builtin.command: >-
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    {{ kubeadm_init_extra_args | default('', true) }}
  when: not kubeadm_admin_conf.stat.exists
  register: kubeadm_init
  notify: Restart kubelet
