---
- name: Configure Kubernetes apt repository
  ansible.builtin.import_tasks: 10-repo.yml

- name: Install Kubernetes packages
  ansible.builtin.import_tasks: 20-install.yml

- name: Initialize Kubernetes control plane
  ansible.builtin.import_tasks: 30-init.yml

- name: Configure kubeconfig
  ansible.builtin.import_tasks: 40-kubeconfig.yml

- name: Verify Kubernetes control plane
  ansible.builtin.import_tasks: 50-verify.yml
