---
- name: 10-repo - Create apt keyrings directory
  ansible.builtin.file:
    path: "{{ containerd_apt_keyring_dir }}"
    state: directory
    mode: "0755"

- name: 10-repo - Add Docker apt repository key
  ansible.builtin.get_url:
    url: "{{ containerd_apt_key_url }}"
    dest: "{{ containerd_apt_key_path }}"
    mode: "0644"

- name: 10-repo - Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "{{ containerd_apt_repository }}"
    filename: "{{ containerd_apt_repository_filename }}"
    state: present
