---
- name: 20-install - Search for containerd package
  ansible.builtin.command: apt-cache madison {{ containerd_package_name }}={{ containerd_version }}
  register: containerd_package_search
  changed_when: false
  failed_when: containerd_package_search.rc != 0 or containerd_package_search.stdout | length == 0

- name: 20-install - Install containerd
  ansible.builtin.apt:
    name: "{{ containerd_package_name }}={{ containerd_version }}"
    state: present
    update_cache: true

- name: 20-install - Hold containerd package version
  ansible.builtin.dpkg_selections:
    name: "{{ containerd_package_name }}"
    selection: hold
