---
- name: Configure NVIDIA device plugin Helm repository
  ansible.builtin.import_tasks: 10-repo.yml

- name: Install NVIDIA device plugin
  ansible.builtin.import_tasks: 20-install.yml

- name: Verify NVIDIA device plugin
  ansible.builtin.import_tasks: 30-verify.yml
