---
- name: 20-install - Check if NVIDIA device plugin Helm release is installed
  ansible.builtin.command: helm status {{ nvdp_release_name }} -n {{ nvdp_namespace }}
  environment:
    KUBECONFIG: "{{ nvdp_kubeconfig_path }}"
  register: nvdp_helm_status
  changed_when: false
  failed_when: false

- name: 20-install - Install NVIDIA device plugin via Helm
  ansible.builtin.command: >-
    helm upgrade --install {{ nvdp_release_name }} {{ nvdp_chart_ref }}
    --namespace {{ nvdp_namespace }}
    --create-namespace
    --version {{ nvidia_device_plugin_chart_version }}
    -f {{ nvdp_values_file_path }}
  environment:
    KUBECONFIG: "{{ nvdp_kubeconfig_path }}"
  when: nvdp_helm_status.rc != 0

- name: 20-install - Label the node with nvidia.com/gpu.present=true
  ansible.builtin.command: kubectl label node {{ nvdp_node_name }} nvidia.com/gpu.present=true
  environment:
    KUBECONFIG: "{{ nvdp_kubeconfig_path }}"
  register: label_node
  changed_when: "'nvidia.com/gpu.present=true' in label_node.stdout"
  failed_when: label_node.rc != 0
