---
- name: Configure Calico Helm repository
  ansible.builtin.import_tasks: 10-repo.yml

- name: Install Calico
  ansible.builtin.import_tasks: 20-install.yml

- name: Verify Calico
  ansible.builtin.import_tasks: 30-verify.yml
