---
- name: Load kernel modules for Kubernetes
  ansible.builtin.command: "modprobe {{ item }}"
  loop: "{{ common_kernel_modules }}"
  changed_when: false
  failed_when: false
  
- name: Persist kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: "0644"