---
- name: Configure swap
  ansible.builtin.import_tasks: 10-swap.yml

- name: Install common packages
  ansible.builtin.import_tasks: 20-packages.yml

- name: Configure kernel modules
  ansible.builtin.import_tasks: 30-kernel.yml

- name: Configure sysctl
  ansible.builtin.import_tasks: 40-sysctl.yml
