---
- name: Bootstrap WSL host for Kubernetes
  hosts: localhost
  gather_facts: true
  vars_files:
    - ../../versions.yml
  roles:
    - role: 10-1-common
    - role: 10-2-containerd
    - role: 10-3-nvidia_container_toolkit
