---
# ../tasks/handlers/main.yml
containerd_service_name: containerd

# ../tasks/10-repo.yml
containerd_apt_keyring_dir: /etc/apt/keyrings
containerd_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
containerd_apt_key_path: "{{ containerd_apt_keyring_dir }}/docker.asc"
containerd_apt_repository_filename: docker
containerd_apt_repository: "deb [arch={{ sys_arch }} signed-by={{ containerd_apt_key_path }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

# ../tasks/20-install.yml
containerd_package_name: containerd.io

# ../tasks/30-config.yml
containerd_config_dir: /etc/containerd
containerd_config_path: "{{ containerd_config_dir }}/config.toml"
containerd_root_dir: /var/lib/containerd
containerd_state_dir: /run/containerd
containerd_systemd_cgroup: true
containerd_sandbox_image: registry.k8s.io/pause:3.10
